name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - latest
  pull_request:
    branches:
      - main
      - latest

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Docker image tag
      id: image_tag
      run: |
        if [[ "${GITHUB_REF##*/}" == "latest" ]]; then
          echo "::set-output name=tag::latest"
        else
          echo "::set-output name=tag::dev"
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./backstage/src/main/docker/buildx
        file: ./backstage/src/main/docker/buildx/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        tags: ${{ secrets.DOCKER_USERNAME }}/spirit:${{ steps.image_tag.outputs.tag }}
